version: '3.8'

services:
  # Ollama - Servidor local de modelos de IA
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    restart: unless-stopped
    networks:
      - ai-network

  # Redis - Cache opcional para respostas
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - cache

  # Nginx - Proxy reverso opcional
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - proxy

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  ai-network:
    driver: bridge 